name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}
author: LazyGon
softdepend: ["AltManager"]
api-version: '1.14'

commands:
  scoreboardutils:
    description: "Main command of this plugin."
    aliases: [scoreutils]

permissions:
  scoreboardutils.ranking:
    description: Permission for command /scoreboardutils ranking <objective> [page]
    default: op